apiVersion: v1
kind: Template
metadata:
  name: perf-report-gen-engine-template
  annotations:
    description: "Description"
    iconClass: "perfchart"
    tags: "perfchart"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      jmeter_report: perfchart-${FILTER}
    name: perfchart-${FILTER}
  spec:
    selector:
      jmeter_report: perfchart-${FILTER} 
    replicas: 1
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          jmeter_report: perfchart-${FILTER}
      spec:
        containers:
        - image: jimmyxiong/perfchart
          command: [ "sh", "-c", "tail -f /dev/null" ]
          imagePullPolicy: Always
          name: perfchart 
          ports:
          - containerPort: 8000 
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always 
        securityContext: {}
    test: false
parameters:
  - name: FILTER
    description: "use to filter them for removing after test finished"
    value: "100"
labels:
  jmeter_report: perfchart-${FILTER} 
