apiVersion: v1
kind: Template
metadata:
  name: jmeter-master-template
  annotations:
    description: "Description"
    iconClass: "jmeter"
    tags: "jmeter"
objects:
-   apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      generation: 1
      labels:
        run: jmeter-master-${FILTER}
        jmeter_mode: master-${FILTER}
      name: jmeter-master-${FILTER}
    spec:
      replicas: 1
      selector:
        run: jmeter-master
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: jmeter-master
        spec:
          containers:
          - image: registry.cn-hangzhou.aliyuncs.com/suplinux/jmeter-master
            command: [ "/bin/bash", "-c", "--" ]
            args: [ "while true; do sleep 30; done;" ]
            imagePullPolicy: Always
            name: jmeter-master
            ports:
            - containerPort: 60000
              protocol: TCP
            volumeMounts:
              - name: loadtest
                mountPath: /jmeter/load_test
                subPath: "load_test"
          volumes:
          - name: loadtest
            configMap:
             name: jmeter-load-test-${FILTER}
            resources: {}
parameters:
  - name: FILTER
    description: "use to filter out them for removing after test finished"
    value: "100"
labels:
  jmeter: jmeter-master
