apiVersion: v1
kind: Template
metadata:
  name: jmeter-slave-template
  annotations:
    description: "Description"
    iconClass: "jmeter"
    tags: "jmeter"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      jmeter_mode: slaves-${FILTER}
    name: jmeter-slaves-${FILTER}
  spec:
    replicas: ${NUMBER} 
    selector:
      jmeter_mode: slaves-${FILTER}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          jmeter_mode: slaves-${FILTER}
      spec:
        containers:
        - image: registry.cn-hangzhou.aliyuncs.com/suplinux/jmeter-slave
          imagePullPolicy: Always
          name: jmeter-slave
          ports:
          - containerPort: 50000
            protocol: TCP
          - containerPort: 1099
            protocol: TCP
          resources:
            requests:
              memory: ${MEM}
              cpu: ${CPU}
            limits:
              memory: 2000Mi
              cpu: 2000m
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
    test: false
parameters:
  - name: FILTER
    description: "use to filter out them for removing after test finished"
    value: "100"
  - name: NUMBER 
    description: "the number of JMeter slave instances will be launched"
    value: "2"
  - name: CPU 
    description: "the number of each Jmeter slave cpu"
    value: "2000m"
  - name: MEM
    description: "the number of each JMeter slave mem"
    value: "2000Mi"
labels:
  jmeter: jmeter-slaves
